[versions]
kotlin = "1.6.20"

[libraries]
kord-core = "dev.kord:kord-core:0.8.0-M14"

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"

slf4j-simple = "org.slf4j:slf4j-simple:1.7.36"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.1" }